# Generated by Django 3.2.13 on 2023-09-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
